import turtle
t = turtle.Turtle()
turtle.Screen().setup(500,550)
turtle.Screen().title("Happy Diwali")
turtle.Screen().bgcolor('black')
t.pencolor('blue')
t.fillcolor('orange')
t.begin_fill()
t.speed(50)
t.pensize(8)
t.right(60)
t.forward(200)
t.goto(0,0)
t.right(60)
t.forward(200)
t.left(80)
t.circle(160, 78)
t.end_fill()
def set_position(x, y):
    t.penup()
    t.goto(x, y)
    t.pendown()
t.pensize(10)
set_position(-43,-70)
t.right(60)
t.circle(75, 68)
set_position(15,-170)
t.pensize(8)
t.circle(30)
def star():
    t.pensize(2)
    t.pencolor('red')
    t.fillcolor('yellow')
    t.begin_fill()
    for i in range(5):
        t.forward(30)
        t.right(144)
    t.end_fill()
    t.pensize(10)
    t.pencolor('red')
def curly_star(setheading, circle_x, circle_y):
    set_position(0,10)
    t.setheading(setheading)
    t.circle(circle_x,circle_y)
    star()
def straight_star(setheading, forward):
    set_position(0,10)
    t.setheading(setheading)
    t.forward(forward)
    star()
curly_star(145, 75, 60)
curly_star(120, 150,60)
curly_star(95, 200, 60)
straight_star(90,200)
curly_star(85, -200, 60)
curly_star(60, -150, 60)
curly_star(35, -75, 60)
#we are printing happy diwali and lets create new name in this program
set_position(0,330)
t.pencolor('orange')
t.write("Let's create new",align="center",font=("Arial", 40, "normal"))
set_position(0,-350)
t.pencolor('pink')
t.write("Happy Diwali",align="center",font=("Arial", 40, "normal"))

set_position(-10,-270)
star()
set_position(-10,300)
star()
def draw_firework(x,y):
    t.penup()
    t.goto(x,y)
    t.pendown()
    for _ in range(36):
        t.color("orange")
        t.forward(50)
        t.right(170)
draw_firework(-200, 200)

draw_firework(200, 200)

draw_firework(-200, -200)

draw_firework(200, -200)
turtle.done()